groups:
  - name: example-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(hello_world_requests_total[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "More than 1 request/sec to hello_world in the last 1 minute."